### ISSUE TITLE
Issue for testing CircuitPythonLibrarians tag.

### ISSUE THREAD

**Issue by kattni** [adafruit/Adafruit_CircuitPython_TestRepo#37]
This issue exists solely to find out whether someone outside the org/CPLibians group can tag CPLibians in a reply to an issue and have it work properly.

Please ignore it, it will be closed as soon as we determine the situation.

**Comment by KeithTheEE** [comment]
Going to give this a whirl, @CircuitPythonLibrarians

**Comment by kattni** [comment]
Turns out it's not possible the way GitHub designed teams. Thanks for your help with this anyway!
